a function that delete products
GSG-FC03/Cosmetics-Store pull request #83
Opened 2021-08-11 15:06 UTC by EmanHass

relates #76

2021-08-11 16:09 UTC, MMansour87 approved these changes

2021-08-11 16:12 UTC, MMansour87 requested changes
Well Done
Just need to move this code inside 'window.onclick'  of my issue #75, so no code contradiction happen.

2021-08-12 08:40 UTC, abdulrahman-2020 approved these changes, later dismissed

2021-08-12 13:30 UTC, lina-jamal approved these changes

2021-08-12 13:30 UTC, MMansour87 approved these changes

2021-08-12 13:30 UTC, merged