make Description Page responsive
GSG-FC03/Cosmetics-Store pull request #97
Opened 2021-08-12 15:38 UTC by EmanHass

relates #89

2021-08-12 16:17 UTC, MMansour87 submitted a review, later dismissed
Well Done

2021-08-12 17:21 UTC, abdulrahman-2020 submitted a review, later dismissed

2021-08-12 22:18 UTC, mo7amedehab97 submitted a review, later dismissed

2021-08-13 06:53 UTC, abdulrahman-2020 approved these changes, later dismissed

2021-08-13 15:46 UTC, abdulrahman-2020 approved these changes

2021-08-13 16:05 UTC, MMansour87 approved these changes

2021-08-13 16:07 UTC, MMansour87 requested changes
![image](https://user-images.githubusercontent.com/83221547/129387825-c8bb277a-3274-422d-818f-e0d0384518f5.png)
؟؟؟

2021-08-13 16:17 UTC, MMansour87 approved these changes
Well done

2021-08-13 17:25 UTC, merged